django/ll_project/learning_logs/urls.py
"""Define padrões de URL para learning logs"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #Página inicial
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
]

django/ll_project/ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

django/ll_project/learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """Um tópico que um usuário está aprendendo"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Retorna uma representação de string do modelo"""
        return self.text

class Entry(models.Model):
    """Algo específico aprendido sobre um tópico"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        if len(self.text ) < 50:
            """Retorna uma string simples representando a entrada"""
            return self.text
        else:
            """Retorna uma string simples representando a entrada"""
            return f"{self.text[:50]}..."

django/ll_project/learning_logs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

django/ll_project/learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic
from .forms import TopicForm
 
# Create your views here.
def index(request):
    """A página inicial para o Registro de Aprendizagem"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

django/ll_project/learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Logs</a>
    <a href="{% url 'learning_logs:topics' %}">Tópicos</a>
</p>

{% block content %}{% endblock content %}

django/ll_project/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Learning Logs helps you keep track of your learning, for any topic you're interested in.</p>
{% endblock content %}

django/ll_project/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Add a new topic:</p>

<form action={% url "learning_logs:new_topic" %} method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add topic</button>
</form>
{% endblock content %}

django/ll_project/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Tópico {{ topic.text }}</p>

    <p>Entradas:</p>
    <ul>
        {% for entry in entries %}
            <p>{{ entry.date_added|date:'M d, Y H:i'}}</p>
            <p>{{ entry.text|linebreaks }}</p>
        {% empty %}
            <li>Nenhum tópico foi adicionado.</li>
        {% endfor %}
    </ul>
{% endblock content %}

django/ll_project/learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <p>Tópicos</p>
    <ul>
        {% for topic in topics %}
            <a href={% url 'learning_logs:topic' topic.id %}>
            <li>{{ topic.text }}</li>
            </a>
        {% empty %}
            <li>Nenhum tópico foi adicionado.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}